
const initialState = {
  from: "",
  to: "",
  title: "",
  description: "",
  image: null,
  toInIssue: "",
  isLoading: false,
  groupId: null,
  groupInEdit: null,
  groupName: "",
  groupMemberToInvite: "",
  groupAddress: "",
  groupPhone: "",
  groupIdInEdit: "",
  groupNameInEdit: "",
  groupAddressInEdit: "",
  groupPhoneInEdit: "",
  groupInIssuer: null,
  groupInSidebar: null,
  groupsInSidebar: [],
  certificate: {},
  certificateImage: "",
  certificates: [],
  certificatesInIssuer: null,
  certificateInIssue: null,
  group: null,
  groups: [],
  profileInEdit: null,
  profileName: "",
  profileEmail: "",
  profileImage: "",
  profileNameInEdit: "",
  profileEmailInEdit: "",
  profileImageInEdit: "",
}

export default initialState;
