
const initialState = {
  from: "",
  to: "",
  title: "",
  description: "",
  image: null,
  toInIssue: "",
  groupId: null,
  groupInEdit: null,
  groupName: "",
  groupAddress: "",
  groupPhone: "",
  groupIdInEdit: "",
  groupNameInEdit: "",
  groupAddressInEdit: "",
  groupPhoneInEdit: "",
  groupInIssuer: null,
  certificate: {},
  certificateImage: "",
  certificates: [],
  certificatesInIssuer: [],
  certificateInIssue: null,
  group: null,
  groups: [],
  profileName: "",
  profileEmail: "",
  profileImage: "",
}

export default initialState;
